[package]
name = "swc-coverage-instrument-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.140", features = ["derive"] }
wasm-bindgen = { version = "0.2.81", features = ["serde-serialize"] }
swc-coverage-instrument = { version = "0.0.7", path = "../../packages/swc-coverage-instrument" }
serde-wasm-bindgen = "0.4.3"
