[package]
name = "istanbul-oxi-instrument-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
istanbul-oxi-instrument = { version = "0.1.0", path = "../istanbul-oxi-instrument" }
serde-wasm-bindgen = "0.4.2"
