[package]
name = "istanbul-oxi-instrument-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.79"
istanbul-oxi-instrument = { version = "0.1.0", path = "../istanbul-oxi-instrument" }
