[package]
name = "swc-plugin-istanbul-oxi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1.10.0"
regex = "1.5.5"
serde = "1.0.136"
serde_json = "1.0.79"
swc_plugin = { verion = "0.44.0", features = ["quote"] }
