[package]
name = "swc-plugin-istanbul-oxi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
istanbul-oxi-instrument = { version = "0.1.0", path = "../istanbul-oxi-instrument" }
once_cell = "1.10.0"
regex = "1.5.5"
serde = "1.0.136"
serde_json = "1.0.79"
swc_ecma_quote = "0.11.0"
swc_plugin = { version = "0.45.1", features = ["quote"] }
