[package]
name = "swc-plugin-coverage"
version = "0.0.7"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation plugin for SWC"
license = "MIT"
repository = "https://github.com/kwonoj/swc-coverage-instrument"

[lib]
crate-type = ["cdylib"]

[dependencies]
swc-coverage-instrument = { version = "0.0.7", path = "../swc-coverage-instrument" }
serde_json = "1.0.82"
swc_plugin = { version = "0.85.0", features = ["quote"] }
tracing = "0.1.35"
tracing-subscriber = { version = "0.3.15", features = ["fmt"] }
