[package]
name = "swc-coverage-instrument"
version = "0.0.7"
edition = "2021"
authors = ["OJ Kwon <kwon.ohjoong@gmail.com>"]
description = "Istanbul compatible coverage instrumentation visitor for SWC"
license = "MIT"
repository = "https://github.com/kwonoj/swc-coverage-instrument"

[dependencies]
istanbul-oxide = { version = "0.0.7", path = "../istanbul-oxide" }
once_cell = "1.13.0"
regex = "1.6.0"
serde_json = "1.0.82"
serde = { version = "1.0.140", features = ["derive"] }

swc_common = { version = "0.24.2", features = ["sourcemap"] }
swc_ecmascript = { version = "0.184.0", features = ["utils", "visit"] }
swc_ecma_quote = "0.28.0"
tracing = "0.1.35"
swc_ecma_ast = "0.87.0"

[dev-dependencies]
pretty_assertions = "1.2.1"
